export const DATABASE = {
  MODELS: {
    NEWS_ARTICLE_MODEL: "NEWS_ARTICLE_MODEL",
    SOURCE_MODEL: "SOURCE_MODEL",
  },

  COLLECTIONS: {
    NEWS_ARTICLE: "NewsArticle",
    SOURCE: "Source",
  },

  PROVIDERS: {
    CONNECTION: "DATABASE_CONNECTION",
  },
};
